---
# Copy this file to $HOME/.config and rename it to  `plebeians.yml`

# ORG - The name/abbrev of your organizaton
# You will need to set an ENV variable named PLEBEIANS_ORG to this value
ORG:
    data:
        # Should contain:
        # - directory.json
        # - photos/ directory
        path: /path/to/top/level/data/directory

    # The CLI can upload (publish) the data to an FTP site
    # Here be the credentials and paths necessary to accomplish that.
    publish:
        host: ftp.site.org
        username: username
        password: password
        base_path: top/level/directory/where/everthing/gets/sent/to
        file_map:
            # Local Name (Relative to data:path) : Remote Name (Relative to publish:base_path)
            directory.json: data/directory.json
            ORG.pdf: /data/ORGDirectory.pdf
